<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>IntroSkip</AssemblyName>
    <Description>Skips the intro when the game starts</Description>
    <Version>1.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Authors>CrimsonMods, iZastic</Authors>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageProjectUrl>https://github.com/CrimsonMods/IntroSkip</PackageProjectUrl>
    <RootNamespace>IntroSkip</RootNamespace>
  </PropertyGroup>
<Target Name="Thunderstore Copy to Dist" AfterTargets="AfterBuild" Condition=" '$(Configuration' == 'Release'">
		<Copy SourceFiles="$(OutDir)\CrimsonLog.dll" DestinationFolder="$(SolutionDir)/dist" />
	</Target>
  <ItemGroup>
    <Compile Remove="package\**" />
    <EmbeddedResource Remove="package\**" />
    <None Remove="package\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.733" IncludeAssets="compile" />
    <PackageReference Include="VRising.UnhollowedX.Client" Version="1.0.8" />
  </ItemGroup>
  
  <Import Project="$(MSBuildProjectDirectory)\PluginInfo.props" />
  <Import Project="$(MSBuildProjectDirectory)\Manifest.props" />
  
</Project>
